### ISSUE TITLE
Allow explicit setting of swagger basePath via env variable (BASE_PATH)

### ISSUE THREAD

**Issue by jmartasek** [openphacts/OPS_LinkedDataApi#18]
To utilise authentication reverse proxy the swagger basePath needs to be configurable. The diff below actually allows for it:

diff --git a/index.php b/index.php
index 0d7594d..3dc6fa3 100644
--- a/index.php
+++ b/index.php
@@ -35,8 +35,14 @@ if ("/swagger" ==  $Request->getPathWithoutVersionAndExtension()) {
         $swagger = file_get_contents("api-config-files/swagger.json", true);
         $json = json_decode($swagger, true);
         $base = preg_replace(",(.*)/[^/]*$,", '$1/', $Request->getUri());
-	if (isset($_SERVER["HTTP_X_3SCALE_PROXY_SECRET_TOKEN"])) {
-            $base = str_replace("http://", "https://", $base);
+
+        if (isset($_ENV["BASE_PATH"])) {
+           $base = $_ENV["BASE_PATH"];
+        } else {
+            $base = preg_replace(",(.*)/[^/]*$,", '$1/', $Request->getUri());
+            if (isset($_SERVER["HTTP_X_3SCALE_PROXY_SECRET_TOKEN"])) {
+                $base = str_replace("http://", "https://", $base);
+            }
         }
         $json["basePath"] = $base;

**Comment by jmartasek** [comment]
Actually having set BASE_PATH this value should propagate to the results too. E.g. result._about.

**Comment by stain** [comment]
Thanks for your contribution, @jmartasek.

Fix now live in [ops-linkeddataapi](https://hub.docker.com/r/openphacts/ops-linkeddataapi/) Docker image, to update, try:

    docker pull openphacts/ops-linkeddataapi

I added documentation to the [ops-linkeddataapi README](https://github.com/openphacts/OPS_LinkedDataApi/blob/docker/README.md#swagger) - I will also add it to the `docker-compose.yml` comments in ops-platform-setup.

**Comment by jmartasek** [comment]
Thanks Stien. 

There is still the issue pending of having the BASE_PATH value propagate to the results too. E.g. result._about. Not sure if a new issue shall be raised...
